//
//  Champ.swift
//  Help On The Rift 2
//
//  Created by Chao Wang :) on 5/28/15.
//  Copyright (c) 2015 Chao Wang :). All rights reserved.
//

import Foundation
struct Champs {
    var name:String
    var icon: String
    var background: String
    var lore: String
    var Good1:String
    var Good2:String
    var Good3:String
    var Bad1: String
    var Bad2: String
    var Bad3: String
    var GoodWith1: String
    var GoodWith2: String
    var GoodWith3: String
    var Build: [Builds]
}


let NeedUpdate = Champs (name:"Update",
    icon: "Update.png",
    background: "Update.png",
    lore:NoLore,
    Good1: "Update",
    Good2: "Update",
    Good3:  "Update",
    Bad1: "Update",
    Bad2: "Update",
    Bad3: "Update",
    GoodWith1: "Update",
    GoodWith2: "Update",
    GoodWith3: "Update",
    Build:NoBuild)

let Aatrox = Champs(name: "Aatrox",
    icon: "AatroxSquare.png",
    background: "Aatrox_0.png",
    lore:AatroxLore,
    Good1: "Yasuo",
    Good2: "Darius",
    Good3:  "Akali",
    Bad1: "Jax",
    Bad2: "Fiora",
    Bad3: "Pantheon",
    GoodWith1: "Gnar",
    GoodWith2: "Yasuo",
    GoodWith3: "Azir",
    Build:AatroxBuild )

let Ahri = Champs(name: "Ahri",
icon: "AhriSquare.png",
background: "Ahri_0.png",
lore:AhriLore,
Good1: "Karthus",
Good2: "Gragas",
Good3:  "Katarina",
Bad1: "LeBlanc",
Bad2: "Swain",
Bad3: "Diana",
GoodWith1: "Katarina",
GoodWith2: "Ezreal",
GoodWith3: "Aatrox",
Build:AhriBuild )

let Akali = Champs(name: "Akali",
    icon: "AkaliSquare.png",
    background: "Akali_0.png",
lore:AkaliLore,
Good1: "Karthus",
Good2: "Yasuo",
Good3:  "Morgana",
Bad1: "Lee Sin",
Bad2: "Rumble",
Bad3: "Mordekaiser",
GoodWith1: "Diana",
GoodWith2: "LeBlanc",
GoodWith3: "Katarina",
Build:AkaliBuild )

let Alistar = Champs(name: "Alistar",
    icon: "AlistarSquare.png",
    background: "Alistar_0.png",
lore:AlistarLore,
Good1: "Blitzcrank",
Good2: "Leona",
Good3:  "Thresh",
Bad1: "Janna",
Bad2: "Vayne",
Bad3: "Caitlyn",
GoodWith1: "Yasuo",
GoodWith2: "Vayne",
GoodWith3: "Caitlyn",
Build:AlistarBuild )

let Amumu = Champs(name: "Amumu",
icon: "AmumuSquare.png",
background: "Amumu_0.png",
lore:AmumuLore,
Good1: "Blitzcrank",
Good2: "Jax",
Good3:  "Yasuo",
Bad1: "Shyvana",
Bad2: "Lee Sin",
Bad3: "Xin Zhao",
GoodWith1: "Katarina",
GoodWith2: "Nunu",
GoodWith3: "Miss Fortune",
Build:AmumuBuild )

let Anivia = Champs(name: "Anivia",
    icon: "AniviaSquare.png",
    background: "Anivia_0.png",
lore:AniviaLore,
Good1: "Ryze",
Good2: "Lissandra",
Good3:  "Kayle",
Bad1: "Fizz",
Bad2: "Kassadin",
Bad3: "Diana",
GoodWith1: "Jarvan IV",
GoodWith2: "Vayne",
GoodWith3: "Dr. Mundo",
Build:AniviaBuild )

let Annie = Champs(name: "Annie",
    icon: "AnnieSquare.png",
    background: "Annie_0.png",
lore:AnnieLore,
Good1: "Yasuo",
Good2: "Akali",
Good3: "Fizz",
Bad1: "Brand",
Bad2: "Orianna",
Bad3: "LeBlanc",
GoodWith1: "Jinx",
GoodWith2: "Amumu",
GoodWith3: "Lucian",
Build:AnnieBuild )

let Ashe = Champs(name: "Ashe",
    icon: "AsheSquare.png",
    background: "Ashe_0.png",
lore:AsheLore,
Good1: "Bard",
Good2: "Vayne",
Good3:  "Udyr",
Bad1: "Ezreal",
Bad2: "Kha'Zix",
Bad3: "Graves",
GoodWith1: "Thresh",
GoodWith2: "Leona",
GoodWith3: "Zyra",
Build:AsheBuild )

let Azir = Champs(name: "Azir",
    icon: "AzirSquare.png",
    background: "Azir_0.png",
lore:AzirLore,
Good1: "Yasuo",
Good2: "Teemo",
Good3:  "Nasus",
Bad1: "Ziggs",
Bad2: "Talon",
Bad3: "Xerath",
GoodWith1: "Aatrox",
GoodWith2: "Yasuo",
GoodWith3: "Amumu",
Build:AzirBuild )

let Bard = Champs(name: "Bard",
    icon: "BardSquare.png",
    background: "Bard_0.png",
lore:BardLore,
Good1: "",
Good2: "",
Good3:  "",
Bad1: "Morgana",
Bad2: "Blitzcrank",
Bad3: "Teemo",
GoodWith1: "",
GoodWith2: "",
GoodWith3: "",
Build:BardBuild )

let Blitzcrank = Champs(name: "Blitzcrank",
    icon: "BlitzcrankSquare.png",
    background: "Blitzcrank_0.png",
lore:BlitzcrankLore,
Good1: "Sona",
Good2: "Kog'Maw",
Good3:  "Draven",
Bad1: "Leona",
Bad2: "Alistar",
Bad3: "Morgana",
GoodWith1: "Vayne",
GoodWith2: "Ezreal",
GoodWith3: "Jinx",
Build:BlitzcrankBuild )

let Brand = Champs(name: "Brand",
    icon: "BrandSquare.png",
    background: "Brand_0.png",
lore:BrandLore,
Good1: "Annie",
Good2: "Ryze",
Good3:  "Lissandra",
Bad1: "Kassadin",
Bad2: "LeBlanc",
Bad3: "Fizz",
GoodWith1: "Amumu",
GoodWith2: "Jarvan IV",
GoodWith3: "Vladimir",
Build:BrandBuild )

let Braum = Champs(name: "Braum",
    icon: "BraumSquare.png",
    background: "Braum_0.png",
lore:BraumLore,
Good1: "Caitlyn",
Good2: "Blitzcrank",
Good3:  "Miss Fortune",
Bad1: "Morgana",
Bad2: "Zyra",
Bad3: "Lulu",
GoodWith1: "Lucian",
GoodWith2: "Vayne",
GoodWith3: "Yasuo",
Build:BraumBuild )

let Caitlyn = Champs(name: "Caitlyn",
    icon: "CaitlynSquare.png",
    background: "Caitlyn_0.png",
lore:CaitlynLore,
Good1: "Vayne",
Good2: "Quinn",
Good3:  "Graves",
Bad1: "Sivir",
Bad2: "Jinx",
Bad3: "Varus",
GoodWith1: "Nunu",
GoodWith2: "Leona",
GoodWith3: "Thresh",
Build:CaitlynBuild )

let Cassiopeia = Champs(name: "Cassiopeia",
    icon: "CassiopeiaSquare.png",
    background: "Cassiopeia_0.png",
lore:CassiopeiaLore,
Good1: "Ryze",
Good2: "Swain",
Good3:  "Mordekaiser",
Bad1: "Galio",
Bad2: "LeBlanc",
Bad3: "Lux",
GoodWith1: "Teemo",
GoodWith2: "Singed",
GoodWith3: "Yorick",
Build:CassiopeiaBuild )

let ChoGath = Champs(name: "Cho'Gath",
    icon: "ChoGathSquare.png",
    background: "ChoGath_0.png",
lore:ChoGathLore,
Good1: "Yorick",
Good2: "Malphite",
Good3:  "Katarina",
Bad1: "Warwick",
Bad2: "Kog'Maw",
Bad3: "Vayne",
GoodWith1: "Yasuo",
GoodWith2: "Lulu",
GoodWith3: "Teemo",
Build:ChoGathBuild )

let Corki = Champs(name: "Corki",
    icon: "CorkiSquare.png",
    background: "Corki_0.png",
lore:CorkiLore,
Good1: "Jinx",
Good2: "Tristana",
Good3:  "Vayne",
Bad1: "Caitlyn",
Bad2: "Draven",
Bad3: "Varus",
GoodWith1: "Leona",
GoodWith2: "Blitzcrank",
GoodWith3: "Thresh",
Build:CorkiBuild )

let Darius = Champs(name: "Darius",
    icon: "DariusSquare.png",
    background: "Darius_0.png",
lore:DariusLore,
Good1: "Wukong",
Good2: "Riven",
Good3:  "Nasus",
Bad1: "Teemo",
Bad2: "Jayce",
Bad3: "Yorick",
GoodWith1: "Draven",
GoodWith2: "Olaf",
GoodWith3: "Garen",
Build:DariusBuild )

let Diana = Champs(name: "Diana",
    icon: "DianaSquare.png",
    background: "Diana_0.png",
lore:DianaLore,
Good1: "Katarina",
Good2: "Fizz",
    Good3:  "Ahri",
Bad1: "Mordekaiser",
Bad2: "Riven",
Bad3: "Swain",
GoodWith1: "Akali",
GoodWith2: "Kassadin",
GoodWith3: "Leona",
Build:DianaBuild )

let DrMundo = Champs(name: "Dr. Mundo",
    icon: "DrMundoSquare.png",
    background: "DrMundo_0.png",
lore:DrMundoLore,
Good1: "Jax",
Good2: "Nasus",
Good3:  "Amumu",
Bad1: "Kog'Maw",
Bad2: "Darius",
Bad3: "Riven",
GoodWith1: "",
GoodWith2: "",
GoodWith3: "",
Build:DrMundoBuild )

let Draven = Champs(name: "Draven",
    icon: "DravenSquare.png",
    background: "Draven_0.png",
lore:DravenLore,
    Good1: "Ezreal",
Good2: "Vayne",
Good3:  "Jinx",
Bad1: "Varus",
Bad2: "Caitlyn",
Bad3: "Blitzcrank",
GoodWith1: "Darius",
GoodWith2: "Thresh",
GoodWith3: "Leona",
Build:DravenBuild )

let Ekko = Champs(name: "Ekko",
    icon: "EkkoSquare.png",
    background: "Ekko_0.png",
lore:EkkoLore,
Good1: "Rengar",
Good2: "Akali",
Good3:  "Nasus",
Bad1: "LeBlanc",
Bad2: "Cho'Gath",
Bad3: "Diana",
GoodWith1: "",
GoodWith2: "",
GoodWith3: "",
Build:EkkoBuild )

let Elise = Champs(name: "Elise",
    icon: "EliseSquare.png",
    background: "Elise_0.png",
lore:EliseLore,
Good1: "Renekton",
Good2: "Garen",
Good3:  "Pantheon",
Bad1: "Kassadin",
Bad2: "Wukong",
Bad3: "Yorick",
GoodWith1: "Rengar",
GoodWith2: "Leona",
GoodWith3: "Karma",
Build:EliseBuild )

let Evelynn = Champs(name: "Evelynn",
    icon: "EvelynnSquare.png",
    background: "Evelynn_0.png",
lore:EvelynnLore,
Good1: "Gragas",
    Good2: "Karthus",
Good3:  "Sejuani",
Bad1: "Ryze",
Bad2: "Ekko",
Bad3: "Lee Sin",
GoodWith1: "Shen",
    GoodWith2: "Orianna",
GoodWith3: "Cho'Gath",
Build:EvelynnBuild )

let Ezreal = Champs(name: "Ezreal",
    icon: "EzrealSquare.png",
    background: "Ezreal_0.png",
lore:EzrealLore,
Good1: "Jinx",
Good2: "Ashe",
Good3:  "Lucian",
Bad1: "Draven",
Bad2: "Graves",
Bad3: "Caitlyn",
    GoodWith1: "Sona",
GoodWith2: "Leona",
    GoodWith3: "Taric",
Build:EzrealBuild )

let Fiddlesticks = Champs(name: "Fiddlesticks",
    icon: "FiddlesticksSquare.png",
    background: "Fiddlesticks_0.png",
lore:FiddlesticksLore,
Good1: "Katarina",
Good2: "Vladimir",
Good3:  "Akali",
Bad1: "Janna",
Bad2: "Xin Zhao",
Bad3: "Diana",
GoodWith1: "Amumu",
GoodWith2: "Kennen",
    GoodWith3: "Galio",
Build:FiddlesticksBuild )

let Fiora = Champs(name: "Fiora",
    icon: "FioraSquare.png",
    background: "Fiora_0.png",
lore:FioraLore,
Good1: "Yasuo",
Good2: "Gangplank",
Good3:  "Gnar",
Bad1: "Jax",
Bad2: "Pantheon",
Bad3: "Darius",
GoodWith1: "Darius",
GoodWith2: "Volibear",
GoodWith3: "Ahri",
Build:FioraBuild )

let Fizz = Champs(name: "Fizz",
    icon: "FizzSquare.png",
    background: "Fizz_0.png",
lore:FizzLore,
Good1: "Karthus",
Good2: "Twisted Fate",
Good3:  "Vel'Koz",
Bad1: "Kayle",
Bad2: "Lissandra",
Bad3: "Ryze",
GoodWith1: "Nami",
GoodWith2: "Amumu",
GoodWith3: "Aatrox",
Build:FizzBuild )

let Galio = Champs(name: "Galio",
    icon: "GalioSquare.png",
    background: "Galio_0.png",
lore:GalioLore,
Good1: "LeBlanc",
Good2: "Cassiopeia",
Good3:  "Brand",
Bad1: "Irelia",
Bad2: "Udyr",
Bad3: "Malphite",
GoodWith1: "Katarina",
GoodWith2: "Nunu",
GoodWith3: "Fiddlesticks",
Build:GalioBuild )

let Gangplank = Champs(name: "Gangplank",
    icon: "GangplankSquare.png",
    background: "Gangplank_0.png",
lore:GangplankLore,
Good1: "Malzahar",
Good2: "Kassadin",
Good3:  "Lee Sin",
Bad1: "Pantheon",
Bad2: "Fiora",
Bad3: "Riven",
GoodWith1: "Amumu",
GoodWith2: "Twisted Fate",
GoodWith3: "Ahri",
Build:GangplankBuild)

let Garen = Champs(name: "Garen",
    icon: "GarenSquare.png",
    background: "Garen_0.png",
lore:GarenLore,
Good1: "Riven",
Good2: "Akali",
Good3:  "Irelia",
Bad1: "Teemo",
Bad2: "Darius",
Bad3: "Pantheon",
GoodWith1: "Lux",
GoodWith2: "Darius",
GoodWith3: "Aatrox",
Build:GarenBuild )

let Gnar = Champs(name: "Gnar",
    icon: "GnarSquare.png",
    background: "Gnar_0.png",
lore:GnarLore,
Good1: "Soraka",
Good2: "Jax",
Good3:  "Singed",
Bad1: "Pantheon",
Bad2: "Nidalee",
Bad3: "Irelia",
GoodWith1: "Aatrox",
GoodWith2: "Jarvan IV",
GoodWith3: "Orianna",
Build:GnarBuild )

let Gragas = Champs(name: "Gragas",
    icon: "GragasSquare.png",
    background: "Gragas_0.png",
lore:GragasLore,
Good1: "Lux",
Good2: "Karthus",
Good3:  "Kayle",
Bad1: "Yasuo",
Bad2: "Ahri",
Bad3: "LeBlanc",
GoodWith1: "Ashe",
GoodWith2: "Malphite",
GoodWith3: "Sejuani",
Build:GragasBuild )

let Graves = Champs(name: "Graves",
    icon: "GravesSquare.png",
    background: "Graves_0.png",
lore:GravesLore,
Good1: "Varus",
Good2: "Ezreal",
Good3:  "Vayne",
Bad1: "Sivir",
Bad2: "Caitlyn",
Bad3: "Urgot",
GoodWith1: "Taric",
    GoodWith2: "Leona",
GoodWith3: "Thresh",
Build:GravesBuild )

let Hecarim = Champs(name: "Hecarim",
    icon: "HecarimSquare.png",
    background: "Hecarim_0.png",
lore:HecarimLore,
Good1: "Kha'Zix",
Good2: "Ahri",
Good3:  "Janna",
Bad1: "Nasus",
Bad2: "Sejuani",
Bad3: "Aatrox",
GoodWith1: "Orianna",
GoodWith2: "Zilean",
GoodWith3: "Jayce",
Build:HecarimBuild )

let Heimerdinger = Champs(name: "Heimerdinger",
    icon: "HeimerdingerSquare.png",
    background: "Heimerdinger_0.png",
lore:HeimerdingerLore,
Good1: "Katarina",
Good2: "Kassadin",
Good3:  "Diana",
Bad1: "Syndra",
Bad2: "Xerath",
Bad3: "Malzahar",
GoodWith1: "Blitzcrank",
GoodWith2: "Thresh",
GoodWith3: "Vi",
Build:HeimerdingerBuild )

let Irelia = Champs(name: "Irelia",
    icon: "IreliaSquare.png",
    background: "Irelia_0.png",
lore:IreliaLore,
Good1: "Zed",
Good2: "Gnar",
Good3:  "Diana",
Bad1: "Olaf",
Bad2: "Udyr",
    Bad3: "Garen",
GoodWith1: "Riven",
GoodWith2: "Ahri",
GoodWith3: "Akali",
Build:IreliaBuild )

let Janna = Champs(name: "Janna",
    icon: "JannaSquare.png",
    background: "Janna_0.png",
lore:JannaLore,
Good1: "Kennen",
Good2: "Alistar",
    Good3:  "Leona",
Bad1: "Sona",
Bad2: "Fiddlesticks",
Bad3: "Nidalee",
GoodWith1: "Yasuo",
GoodWith2: "Draven",
GoodWith3: "Vayne",
Build:JannaBuild )

let JarvanIV = Champs(name: "Jarvan IV",
    icon: "JarvanIVSquare.png",
    background: "JarvanIV_0.png",
lore:JarvanIVLore,
Good1: "Vladimir",
Good2: "Ryze",
Good3:  "Kayle",
Bad1: "Yorick",
Bad2: "Vi",
Bad3: "Renekton",
GoodWith1: "Orianna",
GoodWith2: "Yasuo",
GoodWith3: "Gnar",
Build:JarvanIVBuild )

let Jax = Champs(name: "Jax",
    icon: "JaxSquare.png",
    background: "Jax_0.png",
lore:JaxLore,
Good1: "Yasuo",
Good2: "Aatrox",
Good3:  "Fiora",
Bad1: "Malphite",
Bad2: "Pantheon",
Bad3: "Ryze",
GoodWith1: "Ahri",
GoodWith2: "Pantheon",
GoodWith3: "Teemo",
Build:JaxBuild )

let Jayce = Champs(name: "Jayce",
    icon: "JayceSquare.png",
    background: "Jayce_0.png",
lore:JayceLore,
Good1: "Darius",
Good2: "Gnar",
Good3:  "Shen",
Bad1: "Yorick",
Bad2: "Xin Zhao",
Bad3: "Fiora",
GoodWith1: "Nidalee",
GoodWith2: "Blitzcrank",
GoodWith3: "Soraka",
Build:JayceBuild )

let Jinx = Champs(name: "Jinx",
    icon: "JinxSquare.png",
    background: "Jinx_0.png",
lore:JinxLore,
Good1: "Caitlyn",
Good2: "Twitch",
Good3:  "Ashe",
Bad1: "Ezreal",
Bad2: "Corki",
Bad3: "Sivir",
GoodWith1: "Leona",
GoodWith2: "Blitzcrank",
GoodWith3: "Thresh",
Build:JinxBuild )

let Kalista = Champs(name: "Kalista",
    icon: "KalistaSquare.png",
    background: "Kalista_0.png",
lore:KalistaLore,
    Good1: "Ezreal",
Good2: "Thresh",
Good3:  "Jinx",
Bad1: "Ashe",
Bad2: "Caitlyn",
Bad3: "Vayne",
GoodWith1: "Blitzcrank",
GoodWith2: "Braum",
GoodWith3: "Annie",
Build:KalistaBuild )

let Karma = Champs(name: "Karma",
    icon: "KarmaSquare.png",
    background: "Karma_0.png",
lore:KarmaLore,
Good1: "Morgana",
Good2: "LeBlanc",
Good3:  "Braum",
Bad1: "Veigar",
Bad2: "Malzahar",
Bad3: "Swain",
GoodWith1: "Jinx",
GoodWith2: "Ezreal",
GoodWith3: "Vayne",
Build:KarmaBuild )

let Karthus = Champs(name: "Karthus",
    icon: "KarthusSquare.png",
    background: "Karthus_0.png",
lore:KarthusLore,
Good1: "Heimerdinger",
Good2: "Karma",
    Good3:  "Yasuo",
Bad1: "Soraka",
Bad2: "Kassadin",
Bad3: "Fizz",
GoodWith1: "Kayle",
GoodWith2: "Amumu",
GoodWith3: "Yorick",
Build:KarthusBuild )

let Kassadin = Champs(name: "Kassadin",
    icon: "KassadinSquare.png",
    background: "Kassadin_0.png",
lore:KassadinLore,
Good1: "Karthus",
Good2: "Lissandra",
Good3:  "Brand",
Bad1: "Talon",
Bad2: "Kennen",
Bad3: "Pantheon",
GoodWith1: "Diana",
GoodWith2: "Aatrox",
GoodWith3: "Lee Sin",
Build:KassadinBuild )

let Katarina = Champs(name: "Katarina",
    icon: "KatarinaSquare.png",
    background: "Katarina_0.png",
lore:KatarinaLore,
Good1: "Karthus",
Good2: "Vel'Koz",
Good3:  "Nidalee",
Bad1: "Diana",
Bad2: "Fiddlesticks",
Bad3: "Lulu",
GoodWith1: "Amumu",
GoodWith2: "Galio",
GoodWith3: "Morgana",
Build:KatarinaBuild )

let Kayle = Champs(name: "Kayle",
    icon: "KayleSquare.png",
    background: "Kayle_0.png",
lore:KayleLore,
Good1: "Zed",
Good2: "Darius",
Good3:  "Fizz",
Bad1: "Annie",
Bad2: "Pantheon",
    Bad3: "Orianna",
GoodWith1: "Ezreal",
GoodWith2: "Karthus",
GoodWith3: "Vayne",
Build:KayleBuild )

let Kennen = Champs(name: "Kennen",
    icon: "KennenSquare.png",
    background: "Kennen_0.png",
lore:KennenLore,
Good1: "Kassadin",
Good2: "Riven",
Good3:  "Renekton",
    Bad1: "Diana",
Bad2: "Janna",
Bad3: "Yorick",
GoodWith1: "Amumu",
GoodWith2: "Vladimir",
GoodWith3: "Fiddlesticks",
Build:KennenBuild )

let KhaZix = Champs(name: "Kha'Zix",
    icon: "KhaZixSquare.png",
    background: "KhaZix_0.png",
lore:KhaZixLore,
Good1: "Kassadin",
Good2: "Ashe",
Good3:  "Yasuo",
Bad1: "Lee Sin",
Bad2: "Yorick",
Bad3: "Jayce",
GoodWith1: "Rengar",
GoodWith2: "Nasus",
GoodWith3: "Xin Zhao",
Build:KhaZixBuild )

let KogMaw = Champs(name: "Kog'Maw",
    icon: "KogMawSquare.png",
    background: "KogMaw_0.png",
lore:KogMawLore,
Good1: "Dr. Mundo",
Good2: "Cho'Gath",
Good3:  "Vayne",
Bad1: "Blitzcrank",
Bad2: "Lucian",
Bad3: "Miss Fortune",
GoodWith1: "Nunu",
GoodWith2: "Thresh",
GoodWith3: "Nami",
Build:KogMawBuild )

let LeBlanc = Champs(name: "LeBlanc",
    icon: "LeBlancSquare.png",
    background: "LeBlanc_0.png",
lore:LeBlancLore,
Good1: "Vel'Koz",
    Good2: "Ahri",
Good3:  "Karthus",
Bad1: "Galio",
Bad2: "Morgana",
Bad3: "Diana",
GoodWith1: "Akali",
GoodWith2: "Udyr",
GoodWith3: "Alistar",
Build:LeBlancBuild )

let LeeSin = Champs(name: "Lee Sin",
    icon: "LeeSinSquare.png",
    background: "LeeSin_0.png",
lore:LeeSinLore,
Good1: "Akali",
Good2: "Shaco",
Good3:  "Wukong",
Bad1: "Trundle",
Bad2: "Udyr",
Bad3: "Pantheon",
GoodWith1: "Yasuo",
GoodWith2: "Teemo",
GoodWith3: "Orianna",
Build:LeeSinBuild )

let Leona = Champs(name: "Leona",
    icon: "LeonaSquare.png",
    background: "Leona_0.png",
lore:LeonaLore,
Good1: "Blitzcrank",
Good2: "Sona",
Good3:  "Varus",
Bad1: "Morgana",
Bad2: "Alistar",
Bad3: "Lulu",
GoodWith1: "Jinx",
GoodWith2: "Caitlyn",
GoodWith3: "Tristana",
Build:LeonaBuild )

let Lissandra = Champs(name: "Lissandra",
    icon: "LissandraSquare.png",
    background: "Lissandra_0.png",
lore:LissandraLore,
Good1: "Katarina",
Good2: "Zed",
Good3:  "Fizz",
Bad1: "Kassadin",
Bad2: "Diana",
Bad3: "Syndra",
GoodWith1: "Sejuani",
    GoodWith2: "Amumu",
GoodWith3: "Trundle",
Build:LissandraBuild )

let Lucian = Champs(name: "Lucian",
    icon: "LucianSquare.png",
    background: "Lucian_0.png",
lore:LucianLore,
    Good1: "Varus",
Good2: "Jinx",
Good3:  "Tristana",
Bad1: "Vayne",
Bad2: "Draven",
Bad3: "Tristana",
GoodWith1: "Braum",
GoodWith2: "Thresh",
GoodWith3: "Leona",
Build:LucianBuild )

let Lulu = Champs(name: "Lulu",
    icon: "LuluSquare.png",
    background: "Lulu_0.png",
lore:LuluLore,
Good1: "Katarina",
Good2: "Thresh",
Good3:  "Leona",
Bad1: "Syndra",
Bad2: "Soraka",
Bad3: "Sona",
GoodWith1: "Vayne",
GoodWith2: "Caitlyn",
GoodWith3: "Draven",
Build:LuluBuild )

let Lux = Champs(name: "Lux",
    icon: "LuxSquare.png",
    background: "Lux_0.png",
lore:LuxLore,
Good1: "Karthus",
Good2: "Ryze",
Good3:  "Heimerdinger",
Bad1: "Talon",
Bad2: "Yasuo",
Bad3: "Fizz",
GoodWith1: "Ezreal",
GoodWith2: "Garen",
GoodWith3: "Jinx",
Build:LuxBuild )

let Malphite = Champs(name: "Malphite",
    icon: "MalphiteSquare.png",
    background: "Malphite_0.png",
lore:MalphiteLore,
Good1: "Jax",
Good2: "Fiora",
Good3:  "Pantheon",
Bad1: "Zac",
Bad2: "Rumble",
Bad3: "Cho'Gath",
GoodWith1: "Yasuo",
GoodWith2: "Orianna",
GoodWith3: "Katarina",
Build:MalphiteBuild )

let Malzahar = Champs(name: "Malzahar",
    icon: "MalzaharSquare.png",
    background: "Malzahar_0.png",
lore:MalzaharLore,
Good1: "Katarina",
Good2: "Yasuo",
Good3:  "Zed",
Bad1: "Gangplank",
Bad2: "Galio",
Bad3: "Morgana",
GoodWith1: "Warwick",
GoodWith2: "Jarvan IV",
GoodWith3: "Amumu",
Build:MalzaharBuild )

let Maokai = Champs(name: "Maokai",
    icon: "MaokaiSquare.png",
    background: "Maokai_0.png",
lore:MaokaiLore,
Good1: "Riven",
Good2: "Kassadin",
Good3:  "Volibear",
Bad1: "Shyvana",
Bad2: "Nasus",
Bad3: "Yorick",
GoodWith1: "Ryze",
GoodWith2: "Swain",
GoodWith3: "Orianna",
Build:MaokaiBuild )

let MasterYi = Champs(name: "Master Yi",
    icon: "MasterYiSquare.png",
    background: "MasterYi_0.png",
lore:MasterYiLore,
Good1: "Karthus",
Good2: "Twisted Fate",
Good3:  "Ashe",
Bad1: "Jax",
Bad2: "Pantheon",
Bad3: "Tryndamere",
GoodWith1: "Ashe",
GoodWith2: "Darius",
GoodWith3: "Aatrox",
Build:MasterYiBuild )

let MissFortune = Champs(name: "Miss Fortune",
    icon: "MissFortuneSquare.png",
    background: "MissFortune_0.png",
lore:MissFortuneLore,
Good1: "Ezreal",
Good2: "Soraka",
Good3:  "Vayne",
Bad1: "Tristana",
Bad2: "Draven",
Bad3: "Braum",
GoodWith1: "Sona",
GoodWith2: "Leona",
GoodWith3: "Blitzcrank",
Build:MissFortuneBuild )

let Mordekaiser = Champs(name: "Mordekaiser",
    icon: "MordekaiserSquare.png",
    background: "Mordekaiser_0.png",
lore:MordekaiserLore,
Good1: "Diana",
Good2: "Akali",
Good3:  "Fizz",
Bad1: "Lux",
Bad2: "Zyra",
Bad3: "Yorick",
GoodWith1: "Yorick",
GoodWith2: "Malphite",
GoodWith3: "Wukong",
Build:MordekaiserBuild )

let Morgana = Champs(name: "Morgana",
    icon: "MorganaSquare.png",
    background: "Morgana_0.png",
lore:MorganaLore,
Good1: "Braum",
Good2: "Blitzcrank",
Good3:  "Leona",
Bad1: "Karma",
Bad2: "Talon",
Bad3: "Akali",
GoodWith1: "Jinx",
GoodWith2: "Caitlyn",
GoodWith3: "Draven",
Build:MorganaBuild )

let Nami = Champs(name: "Nami",
    icon: "NamiSquare.png",
    background: "Nami_0.png",
lore:NamiLore,
Good1: "Draven",
Good2: "Taric",
Good3:  "Thresh",
Bad1: "Lulu",
Bad2: "Ezreal",
Bad3: "Fizz",
GoodWith1: "Vayne",
GoodWith2: "Jinx",
GoodWith3: "Caitlyn",
Build:NamiBuild )

let Nasus = Champs(name: "Nasus",
    icon: "NasusSquare.png",
    background: "Nasus_0.png",
lore:NasusLore,
Good1: "Hecarim",
Good2: "Zed",
Good3:  "Irelia",
Bad1: "Teemo",
Bad2: "Olaf",
Bad3: "Pantheon",
GoodWith1: "Renekton",
GoodWith2: "Kha'Zix",
GoodWith3: "Zed",
Build:NasusBuild )

let Nautilus = Champs(name: "Nautilus",
    icon: "NautilusSquare.png",
    background: "Nautilus_0.png",
lore:NautilusLore,
Good1: "Katarina",
Good2: "Blitzcrank",
    Good3:  "Anivia",
Bad1: "Shyvana",
Bad2: "Shaco",
Bad3: "Kennen",
GoodWith1: "Yasuo",
GoodWith2: "Ezreal",
GoodWith3: "Draven",
Build:NautilusBuild )

let Nidalee = Champs(name: "Nidalee",
    icon: "NidaleeSquare.png",
    background: "Nidalee_0.png",
lore:NidaleeLore,
Good1: "Gnar",
Good2: "Vladimir",
Good3:  "Karthus",
Bad1: "Yasuo",
Bad2: "Pantheon",
Bad3: "Zed",
GoodWith1: "Caitlyn",
GoodWith2: "Jinx",
GoodWith3: "Varus",
Build:NidaleeBuild )

let Nocturne = Champs(name: "Nocturne",
    icon: "NocturneSquare.png",
    background: "Nocturne_0.png",
lore:NocturneLore,
Good1: "Kassadin",
Good2: "Twisted Fate",
Good3:  "Lee Sin",
Bad1: "Lee Sin",
Bad2: "Olaf",
Bad3: "Udyr",
GoodWith1: "Twisted Fate",
GoodWith2: "Shen",
GoodWith3: "Rengar",
Build:NocturneBuild )

let Nunu = Champs(name: "Nunu",
    icon: "NunuSquare.png",
    background: "Nunu_0.png",
lore:NunuLore,
Good1: "Renekton",
Good2: "Heimerdinger",
Good3:  "Yorick",
Bad1: "Cassiopeia",
Bad2: "Sona",
Bad3: "Sivir",
GoodWith1: "Vayne",
GoodWith2: "Kog'Maw",
GoodWith3: "Caitlyn",
Build:NunuBuild )

let Olaf = Champs(name: "Olaf",
    icon: "OlafSquare.png",
    background: "Olaf_0.png",
lore:OlafLore,
Good1: "Dr. Mundo",
Good2: "Irelia",
Good3:  "Nasus",
Bad1: "Kayle",
Bad2: "Yorick",
Bad3: "Elise",
GoodWith1: "Darius",
GoodWith2: "Blitzcrank",
GoodWith3: "Aatrox",
Build:OlafBuild )

let Orianna = Champs(name: "Orianna",
    icon: "OriannaSquare.png",
    background: "Orianna_0.png",
lore:OriannaLore,
Good1: "Ryze",
Good2: "Kayle",
Good3:  "Karthus",
Bad1: "Syndra",
Bad2: "Ziggs",
Bad3: "Zed",
GoodWith1: "Malphite",
GoodWith2: "Yasuo",
GoodWith3: "Jarvan IV",
Build:OriannaBuild )

let Pantheon = Champs(name: "Pantheon",
    icon: "PantheonSquare.png",
    background: "Pantheon_0.png",
lore:PantheonLore,
Good1: "Gangplank",
Good2: "Fiora",
Good3:  "Riven",
Bad1: "Olaf",
Bad2: "Elise",
Bad3: "Shen",
GoodWith1: "Taric",
GoodWith2: "Jax",
GoodWith3: "Blitzcrank",
Build:PantheonBuild )

let Poppy = Champs(name: "Poppy",
    icon: "PoppySquare.png",
    background: "Poppy_0.png",
lore:PoppyLore,
Good1: "Gangplank",
Good2: "Jax",
Good3:  "V",
Bad1: "Olaf",
Bad2: "Darius",
Bad3: "Teemo",
GoodWith1: "Vayne",
GoodWith2: "Sion",
GoodWith3: "Cho'Gath",
Build:PoppyBuild )

let Quinn = Champs(name: "Quinn",
    icon: "QuinnSquare.png",
    background: "Quinn_0.png",
lore:QuinnLore,
Good1: "Vayne",
Good2: "Jinx",
Good3:  "Riven",
Bad1: "Caitlyn",
Bad2: "Varus",
Bad3: "Caitlyn",
GoodWith1: "Leona",
GoodWith2: "Thresh",
GoodWith3: "Nami",
Build:QuinnBuild )

let Rammus = Champs(name: "Rammus",
    icon: "RammusSquare.png",
    background: "Rammus_0.png",
lore:RammusLore,
Good1: "Tryndamere",
Good2: "Master Yi",
Good3:  "Yasuo",
Bad1: "Trundle",
Bad2: "Ekko",
    Bad3: "Vi",
GoodWith1: "Shen",
GoodWith2: "Ashe",
GoodWith3: "Ahri",
Build:RammusBuild )

let RekSai = Champs(name: "Rek'Sai",
    icon: "RekSaiSquare.png",
    background: "RekSai_0.png",
lore:RekSaiLore,
Good1: "Evelynn",
Good2: "Rengar",
Good3:  "Nasus",
Bad1: "Fizz",
Bad2: "Jayce",
Bad3: "Darius",
GoodWith1: "Fizz",
GoodWith2: "Rammus",
GoodWith3: "Rengar",
Build:RekSaiBuild )

let Renekton = Champs(name: "Renekton",
    icon: "RenektonSquare.png",
    background: "Renekton_0.png",
lore:RenektonLore,
Good1: "Fiora",
Good2: "Jax",
Good3:  "Akali",
Bad1: "Vayne",
Bad2: "Trundle",
Bad3: "Elise",
GoodWith1: "Nasus",
GoodWith2: "Aatrox",
GoodWith3: "Lulu",
Build:RenektonBuild )

let Rengar = Champs(name: "Rengar",
    icon: "RengarSquare.png",
    background: "Rengar_0.png",
lore:RengarLore,
Good1: "Kha'Zix",
Good2: "Nasus",
Good3:  "Aatrox",
Bad1: "Jax",
Bad2: "Fiora",
Bad3: "Pantheon",
GoodWith1: "Kha'Zix",
GoodWith2: "Orianna",
GoodWith3: "Elise",
Build:RengarBuild )

let Riven = Champs(name: "Riven",
    icon: "RivenSquare.png",
    background: "Riven_0.png",
lore:RivenLore,
Good1: "Katarina",
Good2: "Vi",
Good3:  "Yasuo",
Bad1: "Garen",
Bad2: "Pantheon",
Bad3: "Kennen",
GoodWith1: "Yasuo",
GoodWith2: "Irelia",
GoodWith3: "Orianna",
Build:RivenBuild )

let Rumble = Champs(name: "Rumble",
    icon: "RumbleSquare.png",
    background: "Rumble_0.png",
    lore:RumbleLore,
    Good1: "Malphite",
    Good2: "Nasus",
    Good3:  "Akali",
    Bad1: "Yorick",
    Bad2: "Viktor",
    Bad3: "Darius",
    GoodWith1: "Amumu",
    GoodWith2: "Jarvan IV",
    GoodWith3: "Sejuani",
    Build:RumbleBuild )

let Ryze = Champs(name: "Ryze",
    icon: "RyzeSquare.png",
    background: "Ryze_0.png",
lore:RyzeLore,
Good1: "Fizz",
Good2: "Jax",
Good3:  "Nasus",
Bad1: "Cassiopeia",
Bad2: "Xerath",
Bad3: "Ziggs",
GoodWith1: "Maokai",
GoodWith2: "Lee Sin",
GoodWith3: "Udyr",
Build:RyzeBuild )

let Sejuani = Champs(name: "Sejuani",
    icon: "SejuaniSquare.png",
    background: "Sejuani_0.png",
lore:SejuaniLore,
Good1: "Hecarim",
Good2: "Katarina",
Good3:  "Aatrox",
Bad1: "Xin Zhao",
Bad2: "Evelynn",
Bad3: "Vi",
GoodWith1: "Lissandra",
GoodWith2: "Katarina",
GoodWith3: "Talon",
Build:SejuaniBuild )

let Shaco = Champs(name: "Shaco",
    icon: "ShacoSquare.png",
    background: "Shaco_0.png",
lore:ShacoLore,
Good1: "Amumu",
Good2: "Nautilus",
Good3:  "Master Yi",
Bad1: "Lee Sin",
Bad2: "Udyr",
Bad3: "Vi",
GoodWith1: "Blitzcrank",
GoodWith2: "Shen",
GoodWith3: "Teemo",
Build:ShacoBuild )

let Shen = Champs(name: "Shen",
    icon: "ShenSquare.png",
    background: "Shen_0.png",
lore:ShenLore,
Good1: "Pantheon",
Good2: "Malphite",
Good3:  "Fiora",
Bad1: "Yorick",
Bad2: "Jayce",
Bad3: "Warwick",
GoodWith1: "Twisted Fate",
GoodWith2: "Zed",
GoodWith3: "Akali",
Build:ShenBuild )

let Shyvana = Champs(name: "Shyvana",
    icon: "ShyvanaSquare.png",
    background: "Shyvana_0.png",
lore:ShyvanaLore,
Good1: "Nautilus",
Good2: "Amumu",
Good3:  "Maokai",
Bad1: "Olaf",
Bad2: "Trundle",
Bad3: "Pantheon",
GoodWith1: "Yasuo",
GoodWith2: "Shen",
GoodWith3: "Jarvan IV",
Build:ShyvanaBuild )

let Singed = Champs(name: "Singed",
    icon: "SingedSquare.png",
    background: "Singed_0.png",
lore:SingedLore,
Good1: "Jax",
Good2: "Fiora",
Good3:  "Karthus",
Bad1: "Teemo",
Bad2: "Kayle",
Bad3: "Elise",
GoodWith1: "Cassiopeia",
GoodWith2: "Volibear",
GoodWith3: "Teemo",
Build:SingedBuild )

let Sion = Champs(name: "Sion",
    icon: "SionSquare.png",
    background: "Sion_0.png",
lore:SionLore,
Good1: "LeBlanc",
Good2: "Kassadin",
Good3:  "Annie",
Bad1: "Garen",
Bad2: "Riven",
Bad3: "Pantheon",
GoodWith1: "Pantheon",
GoodWith2: "Talon",
GoodWith3: "Poppy",
Build:SionBuild )

let Sivir = Champs(name: "Sivir",
    icon: "SivirSquare.png",
    background: "Sivir_0.png",
lore:SivirLore,
Good1: "Caitlyn",
Good2: "Jinx",
Good3:  "Blitzcrank",
Bad1: "Vayne",
Bad2: "Draven",
Bad3: "Twitch",
GoodWith1: "Thresh",
GoodWith2: "Soraka",
GoodWith3: "Leona",
Build:SivirBuild )

let Skarner = Champs(name: "Skarner",
    icon: "SkarnerSquare.png",
    background: "Skarner_0.png",
lore:SkarnerLore,
Good1: "Mordekaiser",
Good2: "Warwick",
Good3:  "Vi",
Bad1: "Morgana",
Bad2: "Cho'Gath",
Bad3: "Xin Zhao",
GoodWith1: "Jayce",
GoodWith2: "Thresh",
GoodWith3: "Heimerdinger",
Build:SkarnerBuild )

let Sona = Champs(name: "Sona",
    icon: "SonaSquare.png",
    background: "Sona_0.png",
lore:SonaLore,
Good1: "Janna",
Good2: "Trundle",
Good3:  "Morgana",
Bad1: "Blitzcrank",
Bad2: "Leona",
Bad3: "Thresh",
GoodWith1: "Ezreal",
GoodWith2: "Caitlyn",
GoodWith3: "Miss Fortune",
Build:SonaBuild )

let Soraka = Champs(name: "Soraka",
    icon: "SorakaSquare.png",
    background: "Soraka_0.png",
lore:SorakaLore,
Good1: "Karthus",
Good2: "Yasuo",
Good3:  "Urgot",
Bad1: "Gnar",
Bad2: "Miss Fortune",
Bad3: "Blitzcrank",
GoodWith1: "Ezreal",
GoodWith2: "Sivir",
GoodWith3: "Urgot",
Build:SorakaBuild )

let Swain = Champs(name: "Swain",
    icon: "SwainSquare.png",
    background: "Swain_0.png",
lore:SwainLore,
Good1: "Vladimir",
Good2: "Yasuo",
Good3:  "Ahri",
Bad1: "Viktor",
Bad2: "Syndra",
Bad3: "LeBlanc",
GoodWith1: "Vladimir",
GoodWith2: "Maokai",
GoodWith3: "Alistar",
Build:SwainBuild )

let Syndra = Champs(name: "Syndra",
    icon: "SyndraSquare.png",
    background: "Syndra_0.png",
lore:SyndraLore,
Good1: "Heimerdinger",
Good2: "Akali",
Good3:  "Ziggs",
Bad1: "Fizz",
Bad2: "Kayle",
Bad3: "Talon",
    GoodWith1: "Zac",
GoodWith2: "Nami",
GoodWith3: "Zilean",
Build:SyndraBuild )

let TahmKench = Champs(name: "Tahm Kench",
    icon: "TahmKenchSquare.png",
    background: "TahmKench_0.png",
    lore:TahmKenchLore,
    Good1: "Update",
    Good2: "Update",
    Good3:  "Update",
    Bad1: "Update",
    Bad2: "Update",
    Bad3: "Update",
    GoodWith1: "Update",
    GoodWith2: "Update",
    GoodWith3: "Update",
    Build:NoBuild )

let Talon = Champs(name: "Talon",
    icon: "TalonSquare.png",
    background: "Talon_0.png",
lore:TalonLore,
Good1: "Kassadin",
Good2: "Lux",
Good3:  "Veigar",
    Bad1: "Lee Sin",
Bad2: "Kayle",
Bad3: "Mordekaiser",
GoodWith1: "Zed",
GoodWith2: "Darius",
GoodWith3: "Sejuani",
Build:TalonBuild )

let Taric = Champs(name: "Taric",
    icon: "TaricSquare.png",
    background: "Taric_0.png",
lore:TaricLore,
Good1: "Zed",
Good2: "Ashe",
Good3:  "Miss Fortune",
Bad1: "Sivir",
Bad2: "Lulu",
Bad3: "Morgana",
GoodWith1: "Graves",
GoodWith2: "Ezreal",
GoodWith3: "Vayne",
Build:TaricBuild )

let Teemo = Champs(name: "Teemo",
    icon: "TeemoSquare.png",
    background: "Teemo_0.png",
lore:TeemoLore,
Good1: "Tryndamere",
Good2: "Nasus",
Good3:  "Singed",
Bad1: "Yorick",
Bad2: "Pantheon",
Bad3: "Akali",
GoodWith1: "Cassiopeia",
GoodWith2: "Lee Sin",
GoodWith3: "Blitzcrank",
Build:TeemoBuild )

let Thresh = Champs(name: "Thresh",
    icon: "ThreshSquare.png",
    background: "Thresh_0.png",
lore:ThreshLore,
Good1: "Draven",
Good2: "Blitzcrank",
Good3:  "Sona",
Bad1: "Lulu",
Bad2: "Morgana",
Bad3: "Alistar",
GoodWith1: "Vayne",
GoodWith2: "Lucian",
GoodWith3: "Draven",
Build:ThreshBuild )

let Tristana = Champs(name: "Tristana",
    icon: "TristanaSquare.png",
    background: "Tristana_0.png",
lore:TristanaLore,
Good1: "Miss Fortune",
Good2: "Vayne",
    Good3:  "Lucian",
Bad1: "Corki",
Bad2: "Diana",
Bad3: "Lucian",
GoodWith1: "Leona",
GoodWith2: "Thresh",
GoodWith3: "Nami",
Build:TristanaBuild )

let Trundle = Champs(name: "Trundle",
    icon: "TrundleSquare.png",
    background: "Trundle_0.png",
lore:TrundleLore,
    Good1: "Lee Sin",
    Good2: "Renekton",
    Good3:  "Shyvana",
    Bad1: "Vladimir",
    Bad2: "Darius",
    Bad3: "Pantheon",
    GoodWith1: "Anivia",
    GoodWith2: "Aatrox",
    GoodWith3: "Lissandra",
Build:TrundleBuild )

let Tryndamere = Champs(name: "Tryndamere",
    icon: "TryndamereSquare.png",
    background: "Tryndamere_0.png",
lore:TryndamereLore,
Good1: "Yasuo",
    Good2: "Master Yi",
Good3:  "Aatrox",
Bad1: "Teemo",
Bad2: "Rammus",
Bad3: "Pantheon",
    GoodWith1: "Aatrox",
GoodWith2: "Ashe",
GoodWith3: "Zilean",
Build:TryndamereBuild )

let TwistedFate = Champs(name: "Twisted Fate",
    icon: "TwistedFateSquare.png",
    background: "TwistedFate_0.png",
lore:TwistedFateLore,
Good1: "Ryze",
Good2: "Lissandra",
Good3:  "Aatrox",
Bad1: "Fizz",
Bad2: "Diana",
Bad3: "Kassadin",
GoodWith1: "Nocturne",
GoodWith2: "Shen",
GoodWith3: "Gangplank",
Build:TwistedFateBuild )

let Twitch = Champs(name: "Twitch",
    icon: "TwitchSquare.png",
    background: "Twitch_0.png",
lore:TwitchLore,
Good1: "Ezreal",
Good2: "Vayne",
Good3:  "Sivir",
Bad1: "Lee Sin",
Bad2: "Caitlyn",
Bad3: "Corki",
GoodWith1: "Braum",
GoodWith2: "Leona",
GoodWith3: "Taric",
Build:TwitchBuild )

let Udyr = Champs(name: "Udyr",
    icon: "UdyrSquare.png",
    background: "Udyr_0.png",
lore:UdyrLore,
Good1: "Irelia",
Good2: "Lee Sin",
    Good3:  "Pantheon",
Bad1: "Ashe",
Bad2: "Elise",
Bad3: "Jax",
GoodWith1: "LeBlanc",
GoodWith2: "Ryze",
GoodWith3: "Amumu",
Build:UdyrBuild )

let Urgot = Champs(name: "Urgot",
    icon: "UrgotSquare.png",
    background: "Urgot_0.png",
lore:UrgotLore,
Good1: "Graves",
Good2: "Jinx",
Good3:  "Vayne",
Bad1: "Soraka",
Bad2: "Vayne",
Bad3: "Twitch",
GoodWith1: "Soraka",
GoodWith2: "Taric",
GoodWith3: "Thresh",
Build:UrgotBuild )

let Varus = Champs(name: "Varus",
    icon: "VarusSquare.png",
    background: "Varus_0.png",
lore:VarusLore,
Good1: "Draven",
Good2: "Jinx",
    Good3:  "Caitlyn",
Bad1: "Graves",
Bad2: "Lucian",
Bad3: "Sivir",
GoodWith1: "Leona",
GoodWith2: "Thresh",
GoodWith3: "Nami",
Build:VarusBuild )

let Vayne = Champs(name: "Vayne",
    icon: "VayneSquare.png",
    background: "Vayne_0.png",
lore:VayneLore,
    Good1: "Lucian",
    Good2: "Renekton",
    Good3:  "Sivir",
    Bad1: "Caitlyn",
    Bad2: "Quinn",
    Bad3: "Draven",
GoodWith1: "Nami",
GoodWith2: "Thresh",
    GoodWith3: "Nunu",
Build:VayneBuild )

let Veigar = Champs(name: "Veigar",
    icon: "VeigarSquare.png",
    background: "Veigar_0.png",
lore:VeigarLore,
Good1: "Karthus",
Good2: "Cassiopeia",
Good3:  "Katarina",
Bad1: "Fizz",
Bad2: "Talon",
Bad3: "Zed",
GoodWith1: "Warwick",
GoodWith2: "LeBlanc",
GoodWith3: "Amumu",
Build:VeigarBuild )

let VelKoz = Champs(name: "Vel'Koz",
    icon: "VelKozSquare.png",
    background: "VelKoz_0.png",
lore:VelKozLore,
Good1: "Heimerdinger",
Good2: "Teemo",
Good3:  "Orianna",
Bad1: "Yasuo",
    Bad2: "LeBlanc",
Bad3: "Fizz",
GoodWith1: "Amumu",
GoodWith2: "Leona",
GoodWith3: "Aatrox",
Build:VelKozBuild )

let Vi = Champs(name: "Vi",
    icon: "ViSquare.png",
    background: "Vi_0.png",
lore:ViLore,
Good1: "Zac",
Good2: "Katarina",
Good3:  "Jarvan IV",
Bad1: "Riven",
Bad2: "Pantheon",
Bad3: "Lee Sin",
GoodWith1: "Caitlyn",
GoodWith2: "Yasuo",
GoodWith3: "Orianna",
Build:ViBuild )

let Viktor = Champs(name: "Viktor",
    icon: "ViktorSquare.png",
    background: "Viktor_0.png",
lore:ViktorLore,
Good1: "Swain",
Good2: "Katarina",
Good3:  "Rumble",
Bad1: "Ziggs",
Bad2: "Syndra",
Bad3: "Zed",
GoodWith1: "Jarvan IV",
    GoodWith2: "Amumu",
GoodWith3: "Aatrox",
Build:ViktorBuild )

let Vladimir = Champs(name: "Vladimir",
    icon: "VladimirSquare.png",
    background: "Vladimir_0.png",
lore:VladimirLore,
Good1: "Zed",
Good2: "Gnar",
Good3:  "Singed",
Bad1: "Swain",
Bad2: "Fiddlesticks",
Bad3: "Jarvan IV",
GoodWith1: "Swain",
GoodWith2: "Kennen",
GoodWith3: "Lulu",
Build:VladimirBuild )

let Volibear = Champs(name: "Volibear",
    icon: "VolibearSquare.png",
    background: "Volibear_0.png",
lore:VolibearLore,
Good1: "Riven",
Good2: "Nasus",
Good3:  "Olaf",
Bad1: "Teemo",
Bad2: "Elise",
Bad3: "Darius",
GoodWith1: "Ashe",
GoodWith2: "Yasuo",
GoodWith3: "Draven",
Build:VolibearBuild )

let Warwick = Champs(name: "Warwick",
    icon: "WarwickSquare.png",
    background: "Warwick_0.png",
lore:WarwickLore,
Good1: "Cho'Gath",
Good2: "Shen",
Good3:  "Renekton",
Bad1: "Yorick",
Bad2: "Renekton",
Bad3: "Kayle",
GoodWith1: "Malzahar",
GoodWith2: "Katarina",
GoodWith3: "Veigar",
Build:WarwickBuild )

let Wukong = Champs(name: "Wukong",
    icon: "WukongSquare.png",
    background: "Wukong_0.png",
lore:WukongLore,
Good1: "Zed",
Good2: "Teemo",
Good3:  "Gnar",
Bad1: "Lee Sin",
Bad2: "Darius",
Bad3: "Pantheon",
GoodWith1: "Yasuo",
GoodWith2: "Orianna",
GoodWith3: "Katarina",
Build:WukongBuild )

let Xerath = Champs(name: "Xerath",
    icon: "XerathSquare.png",
    background: "Xerath_0.png",
lore:XerathLore,
Good1: "Ryze",
Good2: "Heimerdinger",
Good3:  "Ziggs",
Bad1: "Gragas",
    Bad2: "Ahri",
    Bad3: "Zed",
GoodWith1: "Jarvan IV",
GoodWith2: "Quinn",
GoodWith3: "Amumu",
Build:XerathBuild )

let XinZhao = Champs(name: "Xin Zhao",
    icon: "XinZhaoSquare.png",
    background: "XinZhao_0.png",
lore:XinZhaoLore,
Good1: "Yasuo",
Good2: "Vladimir",
Good3:  "Jayce",
Bad1: "Jax",
Bad2: "Malphite",
Bad3: "Pantheon",
GoodWith1: "Yasuo",
GoodWith2: "Blitzcrank",
GoodWith3: "Pantheon",
Build:XinZhaoBuild )

let Yasuo = Champs(name: "Yasuo",
    icon: "YasuoSquare.png",
    background: "Yasuo_0.png",
lore:YasuoLore,
Good1: "Vel'Koz",
Good2: "Nidalee",
Good3:  "Gragas",
Bad1: "Jax",
Bad2: "Fiora",
Bad3: "Malzahar",
GoodWith1: "Malphite",
GoodWith2: "Wukong",
GoodWith3: "Janna",
Build:YasuoBuild )

let Yorick = Champs(name: "Yorick",
    icon: "YorickSquare.png",
    background: "Yorick_0.png",
lore:YorickLore,
Good1: "Teemo",
Good2: "Darius",
Good3:  "Shen",
Bad1: "Cho'Gath",
Bad2: "Nunu",
Bad3: "Trundle",
GoodWith1: "Mordekaiser",
GoodWith2: "Vayne",
GoodWith3: "Cassiopeia",
Build:YorickBuild )

let Zac = Champs(name: "Zac",
    icon: "ZacSquare.png",
    background: "Zac_0.png",
lore:ZacLore,
Good1: "Malphite",
Good2: "Jax",
Good3:  "Katarina",
Bad1: "Vi",
Bad2: "Zilean",
Bad3: "Vladimir",
GoodWith1: "Yasuo",
GoodWith2: "Orianna",
GoodWith3: "Syndra",
Build:ZacBuild )

let Zed = Champs(name: "Zed",
    icon: "ZedSquare.png",
    background: "Zed_0.png",
lore:ZedLore,
Good1: "Nidalee",
Good2: "Veigar",
Good3:  "Brand",
Bad1: "Kayle",
    Bad2: "Jax",
Bad3: "Lissandra",
GoodWith1: "Talon",
GoodWith2: "Shen",
GoodWith3: "Vi",
Build:ZedBuild )

let Ziggs = Champs(name: "Ziggs",
    icon: "ZiggsSquare.png",
    background: "Ziggs_0.png",
lore:ZiggsLore,
Good1: "Azir",
Good2: "Ryze",
Good3:  "Orianna",
Bad1: "LeBlanc",
Bad2: "Talon",
Bad3: "Syndra",
GoodWith1: "Amumu",
    GoodWith2: "Jarvan IV",
GoodWith3: "Leona",
Build:ZiggsBuild )

let Zilean = Champs(name: "Zilean",
    icon: "ZileanSquare.png",
    background: "Zilean_0.png",
lore:ZileanLore,
Good1: "Zac",
Good2: "Zed",
Good3:  "Yasuo",
Bad1: "Annie",
Bad2: "Morgana",
Bad3: "Kassadin",
GoodWith1: "Aatrox",
GoodWith2: "Syndra",
GoodWith3: "Hecarim",
Build:ZileanBuild )

let Zyra = Champs(name: "Zyra",
    icon: "ZyraSquare.png",
    background: "Zyra_0.png",
lore:ZyraLore,
Good1: "Braum",
Good2: "Mordekaiser",
Good3:  "Thresh",
Bad1: "Fizz",
Bad2: "Katarina",
Bad3: "LeBlanc",
GoodWith1: "Ashe",
GoodWith2: "Yasuo",
GoodWith3: "Amumu",
Build:ZyraBuild )

//let  = Champs(name: "",
//icon: ".png",
//background: ".png",
//lore:AatroxLore,
//Good1: "",
//Good2: "",
//Good3:  "",
//Bad1: "",
//Bad2: "",
//Bad3: "",
//GoodWith1: "",
//GoodWith2: "",
//GoodWith3: "",
//Build: )
//
